import pynini
import regex
from transformers import NllbTokenizer

from pywrapfst import SymbolTableView

fst = pynini.Fst.read('analyzeCuzco.windows.fst')
input_symbols: SymbolTableView = fst.input_symbols()
output_symbols: SymbolTableView = fst.output_symbols()

EPSILON_IDX =  0

TOKEN_RE = regex.compile(r"[\p{L}']+|[^\s\p{L}']+|\s+")

# NOTE The base model doesn't encode spaces and instead includes start of word tokens (the token 'be' would also
#   have a complement token '_be' used to represent 'be' at the start of a word). Let me know if this is wrong but according to Claude
#   each Quechua word has exactly one root morpheme (and its always the first morpheme). If thats right then I think
#   the morphemes that start with '=' are the roots and so we don't actually need to create new start of word morphemes
#   as the model can implictly learn that these start of word morphemes represent word boundaries.

# With our current dataset there is only one FST produced token that conflicts with the original vocabulary.
_COLLISIONS_MAP = {
    'SP': '+SP'
}

def _fix_collision(morpheme: str) -> str:
    if morpheme in _COLLISIONS_MAP:
        return _COLLISIONS_MAP[morpheme]
    return morpheme

def run_fst(word: str) -> list[str] | None:
    '''Runs fst and returns the list of morphemes or None if the fst doesn't recognize it.'''
    # build acceptor over the FST's symbol table, one char per arc
    try:
        acceptor = pynini.accep(' '.join(word), token_type=input_symbols)
    except pynini.FstStringCompilationError:
        return None
    
    lattice = pynini.shortestpath(acceptor @ fst)

    if lattice.num_states() == 0:
        return None
    
    morphemes: list[str] = []
    state = lattice.start()

    while True:
        if state == -1:
            raise ValueError(f'running fst on word: {word} caused an error to arise')
        arc = next(iter(lattice.arcs(state)), None)
        if arc is None:
            break
        if arc.olabel != EPSILON_IDX:
            morphemes.append(_fix_collision(output_symbols.find(arc.olabel)))
        state = arc.nextstate

    return morphemes

def get_unique_fst_morphemes(text: str) -> set[str]:
    '''Returns all morpheme types generated by the fst on the given text.'''
    text = text.replace("’", "'")
    morphemes: set[str] = set()

    for match in TOKEN_RE.finditer(text):
        tok = match.group(0)

        # Skip whitespace and pure punctuation
        if tok.isspace() or not any(c.isalpha() for c in tok):
            continue

        # Strip outer apostrophes
        lead_len = len(tok) - len(tok.lstrip("'"))
        trail_len = len(tok) - len(tok.rstrip("'"))
        core = tok[lead_len : len(tok) - trail_len] if trail_len else tok[lead_len:]

        if len(core) == 0:
            continue

        result = run_fst(core)
        if result is not None:
            morphemes.update(result)

    return morphemes

def encode_text(text: str, nllb_tokenizer: NllbTokenizer) -> list[str]:
    '''
    Encodes the text using the fst and falls back to the nllb_tokenizer for text that isn't words or 
    text that the fst doesn't recognize.
    '''
    text = text.replace("’", "'")
    pieces: list[str] = []
    
    for match in TOKEN_RE.finditer(text):
        tok = match.group(0)
        
        if tok.isspace():
            continue

        if not any(c.isalpha() for c in tok):
            pieces.extend(nllb_tokenizer.tokenize(tok))
            continue
        
        # Strip outer apostrophes; route them to NLLB if present
        lead_len = len(tok) - len(tok.lstrip("'"))
        trail_len = len(tok) - len(tok.rstrip("'"))
        core = tok[lead_len: len(tok) - trail_len] if trail_len else tok[lead_len:]
        
        if lead_len > 0:
            pieces.extend(nllb_tokenizer.tokenize(tok[:lead_len]))
        
        if len(core) > 0:
            morphemes = run_fst(core)
            if morphemes is not None:
                pieces.extend(morphemes)
            else:
                # FST failed — fall back to NLLB for this word
                pieces.extend(nllb_tokenizer.tokenize(core))
        
        if trail_len > 0:
            pieces.extend(nllb_tokenizer.tokenize(tok[-trail_len:]))
    
    return pieces